import Head from 'next/head';
import { AiFillGithub, AiFillTwitterCircle, AiFillFolder, AiOutlineLinkedin } from 'react-icons/ai';
import Image from 'next/legacy/image';
import { useState } from 'react';
import deved from '../public/dev-ed-wave.png';


export default function Home() {
  return (
    <div>
      {/*========== Header ==========*/}
      <Head>
        <title>Joshua Reed Portfolio</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-4'>
        <section className='min-h-screen'>
          {/*========== Nav Bar ==========*/}
          <nav className='py-10 mb-12 flex justify-between'>
            <h1>Joshua Reed</h1>
            <ul className='flex items-center'>
              <li>
                <AiFillGithub 
                  onClick={() => ''} 
                  className='cursor-pointer text-2xl'
                />
              </li>
              <li>
                <a className='bg-gradient-to-r from-blue-900 to-blue-500 text-white px-4 py-2 rounded-lg ml-10'
                     href="#">Resume</a>
              </li>
            </ul>
          </nav>

          {/*========== Placeholder Picture ==========*/}
          <div className='relative bg-gradient-to-b from-blue-800 to-white- rounded-full w-80 h-80 mt-10 mx-auto overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} alt='Placeholder Picture' layout='fill' objectFit='cover'/>
          </div>

          {/*========== Home ==========*/}
          <div className='text-center p-10'>
            <h1 className='text-4xl py-1 text-blue-700 font-medium md:text-6xl'>
              Joshua Reed
            </h1>
            <h2 className='text-2xl py-1 md:text-3xl'>
              Computer Science Student
            </h2>
            <p className='text-m py-4 leading-6 text-gray-700 md:text-xl max-w-2xl mx-auto'>
              Hello! My name is Josh Reed. I am a junior Computer Science major at Quinnipiac University.
            </p>
          </div>

          {/*========== Contact Icons ==========*/}
          <div className='text-4xl justify-center gap-10 text-gray-800 flex py-2 lg:text-6xl'>
            <AiFillGithub />
            <AiFillFolder />
            <AiOutlineLinkedin />
          </div>
        </section>


        {/*========== Skills ==========*/}
        <section>
          <div>
            <h2 className='py-3'>
              Skills
            </h2>
            <p className='py-1 text-gray-800 text-center md:text-xl md:max-w-3xl lg:text-xl lg:max-w-4xl mx-auto'>
              Since I first started coding in high school, I have used many different programming 
              languages, softwares, and services. Throughout my courses and projects, I have gained experience with the following:
            </p>
          </div>
          <div className='md:flex gap-20 justify-center'>
            {/*========== Languages ==========*/}
            <div className='text-center p-10 rounded-xl shadow-2xl'>
              <h3 className='text-2xl py-3 text-blue-600 '>Programming Languages:</h3>
              <p className='text-xl py-1 text-gray-800'>Java</p>
              <p className='text-xl py-1 text-gray-800'>C#</p>
              <p className='text-xl py-1 text-gray-800'>Python</p>
              <p className='text-xl py-1 text-gray-800'>SQL</p>
              <p className='text-xl py-1 text-gray-800'>JavaScript</p>
              <p className='text-xl py-1 text-gray-800'>C++</p>
              <p className='text-xl py-1 text-gray-800'>HTML</p>
              <p className='text-xl py-1 text-gray-800'>CSS</p>
            </div>
            {/*========== Softwares ==========*/}
            <div className='text-center p-10 rounded-xl shadow-2xl'>
              <h3 className='text-2xl py-3 text-blue-600 '>Software and Services:</h3>
              <p className='text-xl py-1 text-gray-800'>Visual Studio</p>
              <p className='text-xl py-1 text-gray-800'>Visual Studio Code</p>
              <p className='text-xl py-1 text-gray-800'>Eclipse</p>
              <p className='text-xl py-1 text-gray-800'>Android Studio</p>
              <p className='text-xl py-1 text-gray-800'>Azure Data Studio</p>
              <p className='text-xl py-1 text-gray-800'>Docker</p>
              <p className='text-xl py-1 text-gray-800'>Google Cloud Platform</p>
              <p className='text-xl py-1 text-gray-800'>Microsoft SQL Server</p>
              <p className='text-xl py-1 text-gray-800'>MySQL Workbench</p>
            </div>
          </div>
        </section>

        {/*========== Projects ==========*/}
        <section>
          <div>
            <h2 className='pt-12 pb-3'>
              Projects
            </h2>
          </div>
          <div className='flex flex-col gap-20 py-10 lg:flex-row lg:flex-wrap'>
            {/*========== Project 1 ==========*/}
            <div className='text-center p-10 rounded-xl shadow-2xl basis-1/3 flex-1'>
              <h3 className='text-2xl text-blue-600 py-1'>
                Database Project</h3>
              <p className='text-lg text-gray-800 leading-2'>
                Worked in a small group to create a database using MySQL and Google Cloud. 
                Used Python to parse and upload a public dataset to our database. Created Jupyter Notebooks 
                to display meaningful visualizations and provide information and a description of our dataset.
              </p>
            </div>
            {/*========== Project 2 ==========*/}
            <div className='text-center p-10 rounded-xl shadow-2xl basis-1/3 flex-1'>
              <h3 className='text-xl text-blue-600 py-1'>
                Deal Finder App</h3>
              <p className='text-lg text-gray-800 leading-2'>
                Worked in a team to create a web scraper application that searched for deals. 
                Program accepted user inputted keywords to search for new deals on a deal finding website. 
                Displayed new deals to the user by scraping and parsing HTML data retrieved from the search 
                querys URL.
              </p>
            </div>
            {/*========== Project 3 ==========*/}
            <div className='text-center p-10 rounded-xl shadow-2xl basis-1/3 flex-1'>
              <h3 className='text-xl text-blue-600 py-1'>
                Reminders App</h3>
              <p className='text-lg text-gray-800 leading-2'>
                Developed an Android reminders application that allows users to create, save, delete, 
                and organize events and reminders. My team used Java to develop the app and MySQL to save and 
                manage inputted information. Improved project organization and productivity by utilizing the agile 
                development process, and GitHub for version control.
              </p>
            </div>
            {/*========== Project 4 ==========*/}
            <div className='text-center p-10 rounded-xl shadow-2xl basis-1/3 flex-1'>
              <h3 className='text-xl text-blue-600 py-1'>
                Translate App</h3>
              <p className='text-lg text-gray-800 leading-2'>
                Created an Android application that utilized a REST API to retrieve and display data. 
                Our app uses the Google Translate API to send a phrase and the users chosen output language. 
                The app returns and displays the translated phrase.
              </p>
            </div>
            {/*========== Project 5 ==========*/}
            <div className='text-center p-10 rounded-xl shadow-2xl basis-1/3 flex-1'>
              <h3 className='text-xl text-blue-600 py-1'>
                Platformer Game</h3>
              <p className='text-lg text-gray-800 leading-2'>
                My team was tasked with maintaining and improving an existing platformer game by performing tests, 
                bug fixes, and implementing new features. Gathered user requirements, wrote user stories and tests, 
                and created a backlog of bug fixes and improvements. Implemented and presented our changes throughout 
                multiple sprints. Improved team collaboration, project organization and efficiency by utilizing 
                the scrum cycle development process, and GitHub for version control.
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}