import Head from 'next/head';
import Main from 'components/Main';
import Skills from 'components/Skills';
import Projects from 'components/Projects';
import Contact from 'components/Contact';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Joshua | Portfolio</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}